services:
  - type: web
    name: frisol
    env: python
    buildCommand: pip install -r requirements-vercel.txt
    startCommand: gunicorn api.index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
